# Generated by Django 4.1.10 on 2023-08-24 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
